import { AlertTriangle, ArrowRight, Search, UserCheck, UserPlus, UsersRound } from "lucide-react";
import HrPageHeader from "../../../components/hr/HrPageHeader";

const supervisors = [
  { initials: "FL", name: "Faculty Librarian", department: "University Library", directReports: 12, capacity: 15 },
  { initials: "DI", name: "Director ICT", department: "ICT Directorate", directReports: 9, capacity: 12 },
  { initials: "DH", name: "Director Human Resources", department: "Human Resources", directReports: 7, capacity: 10 },
  { initials: "DP", name: "Director Planning", department: "Planning Directorate", directReports: 8, capacity: 10 },
];

const unassigned = ["Sarah Atim · Research Assistant", "David Mugisha · Records Officer", "Ruth Akello · Graduate Fellow", "Peter Ouma · Driver"];

export default function HrReportingLinesPage() {
  return <><HrPageHeader eyebrow="Reporting Structure" title="Supervisor Assignments" description="Control which supervisor is responsible for each employee’s tasks, timesheets, feedback and performance review." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><UserPlus size={18} /> Assign supervisor</button>} />
    <section className="grid gap-5 md:grid-cols-3"><Status icon={UsersRound} value="148" label="Employees" detail="Total workforce records" /><Status icon={UserCheck} value="144" label="Assigned" detail="97.3% coverage" good /><Status icon={AlertTriangle} value="4" label="Unassigned" detail="Require HR attention" warning /></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><article className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-slate-900">Supervisors and direct reports</h2><p className="mt-1 text-sm text-slate-500">Current reporting-line workload by supervisor</p></div><div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" placeholder="Search supervisor..." className="rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-500" /></div></div><div className="divide-y divide-slate-100">{supervisors.map((supervisor) => { const percentage = Math.round((supervisor.directReports / supervisor.capacity) * 100); return <div key={supervisor.name} className="p-5"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700">{supervisor.initials}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-semibold text-slate-900">{supervisor.name}</p><p className="mt-0.5 text-xs text-slate-500">{supervisor.department}</p></div><button className="inline-flex items-center gap-1 text-sm font-semibold text-blue-600">Manage team <ArrowRight size={15} /></button></div><div className="mt-3 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${percentage}%` }} /></div><span className="text-xs font-semibold text-slate-600">{supervisor.directReports}/{supervisor.capacity}</span></div></div></div></div>; })}</div></article>
      <article className="h-fit rounded-xl border border-amber-200 bg-white shadow-sm"><div className="border-b border-amber-100 bg-amber-50 px-6 py-5"><h2 className="flex items-center gap-2 text-lg font-bold text-amber-900"><AlertTriangle size={20} /> Unassigned employees</h2><p className="mt-1 text-sm text-amber-800">These employees cannot submit records for supervisor approval.</p></div><div className="divide-y divide-slate-100">{unassigned.map((employee) => <div key={employee} className="flex items-center justify-between gap-3 p-5"><p className="text-sm font-medium text-slate-700">{employee}</p><button className="shrink-0 text-sm font-semibold text-blue-600">Assign</button></div>)}</div></article></section>
  </>;
}

function Status({ icon: Icon, value, label, detail, good, warning }: { icon: React.ElementType; value: string; label: string; detail: string; good?: boolean; warning?: boolean }) { const tone = good ? "bg-emerald-50 text-emerald-600" : warning ? "bg-amber-50 text-amber-600" : "bg-blue-50 text-blue-600"; return <article className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`rounded-xl p-3 ${tone}`}><Icon size={23} /></div><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></article>; }
