import Link from "next/link";
import { AlertTriangle, ArrowRight, BarChart3, Building2, CheckCircle2, ClipboardCheck, DatabaseZap, FileText, Target, TrendingUp } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";
import MeStatCard from "../../../components/me/MeStatCard";

const departmentPerformance = [
  { name: "ICT Directorate", score: 89, target: 85, compliance: 92, trend: "+4.2%" },
  { name: "Human Resources", score: 86, target: 85, compliance: 100, trend: "+2.1%" },
  { name: "University Library", score: 82, target: 85, compliance: 88, trend: "+1.5%" },
  { name: "Finance Department", score: 78, target: 85, compliance: 84, trend: "-1.8%" },
  { name: "Planning Directorate", score: 75, target: 85, compliance: 81, trend: "-3.1%" },
];

const flags = [
  { title: "Target below expectation", detail: "Planning Directorate is 10 points below target.", icon: Target, tone: "bg-red-50 text-red-600", href: "/me/targets" },
  { title: "Incomplete reporting", detail: "20 employee records remain uncalculated.", icon: ClipboardCheck, tone: "bg-amber-50 text-amber-600", href: "/me/compliance" },
  { title: "Data-quality exceptions", detail: "Seven records require validation before reporting.", icon: DatabaseZap, tone: "bg-blue-50 text-blue-600", href: "/me/data-quality" },
];

export default function MeDashboardPage() {
  return <><MePageHeader eyebrow="Monitoring & Evaluation Overview" title="Institutional Performance Dashboard" description="Track results against targets, validate reporting quality and turn approved work records into evidence for institutional decision-making." actions={<><Link href="/me/data-quality" className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><DatabaseZap size={18} /> Validate data</Link><Link href="/me/reports" className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><FileText size={18} /> Generate report</Link></>} />
    <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-5"><MeStatCard title="Institutional score" value="82%" description="Three points below target" icon={BarChart3} /><MeStatCard title="Target achievement" value="76%" description="19 of 25 targets on track" icon={Target} tone="emerald" /><MeStatCard title="Reporting compliance" value="86.5%" description="128 of 148 records ready" icon={ClipboardCheck} tone="amber" /><MeStatCard title="Data completeness" value="95.3%" description="Seven exceptions remaining" icon={DatabaseZap} tone="emerald" /><MeStatCard title="Departments at risk" value="2" description="Require management attention" icon={AlertTriangle} tone="red" /></section>

    <section className="mt-7 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><article className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-6 py-5"><div><h2 className="text-lg font-bold text-slate-900">Department performance against target</h2><p className="mt-1 text-sm text-slate-500">Current score, reporting compliance and month-on-month movement</p></div><Link href="/me/departments" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600">Compare all <ArrowRight size={16} /></Link></div><div className="overflow-x-auto"><table className="w-full min-w-200 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Department</th><th className="px-6 py-4">Performance</th><th className="px-6 py-4">Target</th><th className="px-6 py-4">Compliance</th><th className="px-6 py-4">Trend</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{departmentPerformance.map((item) => <tr key={item.name} className="hover:bg-slate-50"><td className="px-6 py-4 font-semibold text-slate-900">{item.name}</td><td className="min-w-45 px-6 py-4"><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Score</span><b className="text-slate-700">{item.score}%</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.score >= item.target ? "bg-emerald-500" : item.score >= 80 ? "bg-blue-600" : "bg-amber-500"}`} style={{ width: `${item.score}%` }} /></div></td><td className="px-6 py-4 font-semibold text-slate-700">{item.target}%</td><td className="px-6 py-4 text-slate-600">{item.compliance}%</td><td className={`px-6 py-4 font-semibold ${item.trend.startsWith("+") ? "text-emerald-600" : "text-red-600"}`}>{item.trend}</td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.score >= item.target ? "bg-emerald-100 text-emerald-700" : item.score >= 80 ? "bg-blue-100 text-blue-700" : "bg-amber-100 text-amber-700"}`}>{item.score >= item.target ? "On target" : item.score >= 80 ? "Watch" : "At risk"}</span></td></tr>)}</tbody></table></div></article>
      <article className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-lg font-bold text-slate-900">Priority findings</h2><p className="mt-1 text-sm text-slate-500">Items requiring validation or follow-up</p></div><div className="divide-y divide-slate-100">{flags.map((flag) => { const Icon = flag.icon; return <div key={flag.title} className="p-5"><div className="flex gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${flag.tone}`}><Icon size={20} /></div><div><p className="text-sm font-semibold text-slate-900">{flag.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{flag.detail}</p><Link href={flag.href} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-blue-600">Investigate <ArrowRight size={14} /></Link></div></div></div>; })}</div></article></section>

    <section className="mt-7 grid gap-6 lg:grid-cols-3"><ResultCard icon={TrendingUp} title="Performance direction" value="+2.6%" description="Institutional performance improved against the previous reporting period." tone="bg-emerald-50 text-emerald-600" /><ResultCard icon={CheckCircle2} title="Targets on track" value="19 / 25" description="Six institutional targets require corrective action or closer monitoring." tone="bg-blue-50 text-blue-600" /><ResultCard icon={Building2} title="Strongest unit" value="ICT" description="ICT Directorate leads current performance at 89%, four points above target." tone="bg-amber-50 text-amber-600" /></section>
  </>;
}

function ResultCard({ icon: Icon, title, value, description, tone }: { icon: React.ElementType; title: string; value: string; description: string; tone: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div className={`rounded-xl p-3 ${tone}`}><Icon size={22} /></div><span className="text-2xl font-bold text-slate-900">{value}</span></div><h3 className="mt-5 font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></article>; }
