import { KeyRound, Mail, MapPin, Phone, Save, ShieldCheck, UserRound } from "lucide-react";
import AdminPageHeader from "../../../components/admin/AdminPageHeader";

export default function AdminProfilePage() {
  return <><AdminPageHeader eyebrow="My Account" title="Administrator Profile" description="Review your account identity, contact information and security access." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><Save size={18} /> Save profile</button>} />
    <div className="grid gap-6 xl:grid-cols-[330px_1fr]"><aside className="h-fit rounded-xl border border-slate-200 bg-white p-6 text-center shadow-sm"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-blue-100 text-3xl font-bold text-blue-700">SA</div><h2 className="mt-4 text-xl font-bold text-slate-900">System Administrator</h2><p className="mt-1 text-sm text-slate-500">ICT Directorate</p><span className="mt-4 inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-semibold text-emerald-700"><ShieldCheck size={15} /> Active administrator</span><div className="mt-6 space-y-3 border-t border-slate-100 pt-6 text-left text-sm text-slate-600"><p className="flex items-center gap-3"><Mail size={17} className="text-slate-400" /> admin@busitema.ac.ug</p><p className="flex items-center gap-3"><Phone size={17} className="text-slate-400" /> +256 700 000 000</p><p className="flex items-center gap-3"><MapPin size={17} className="text-slate-400" /> Main Administration</p></div></aside>
      <div className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="flex items-center gap-2 text-lg font-bold text-slate-900"><UserRound size={20} className="text-blue-600" /> Personal information</h2><p className="mt-1 text-sm text-slate-500">Information associated with your administrator account</p></div><div className="grid gap-5 p-6 md:grid-cols-2"><Field label="First name" value="System" /><Field label="Last name" value="Administrator" /><Field label="Work email" value="admin@busitema.ac.ug" type="email" /><Field label="Phone number" value="+256 700 000 000" /><Field label="Job title" value="Systems Administrator" /><Field label="Department" value="ICT Directorate" /></div></section>
        <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="flex items-center gap-2 text-lg font-bold text-slate-900"><KeyRound size={20} className="text-blue-600" /> Account security</h2><p className="mt-1 text-sm text-slate-500">Password, sessions and multi-factor authentication</p></div><div className="divide-y divide-slate-100"><SecurityRow title="Password" detail="Last changed 32 days ago" action="Change password" /><SecurityRow title="Multi-factor authentication" detail="Required for this administrator account" action="Manage MFA" /><SecurityRow title="Active sessions" detail="One active session on this device" action="Review sessions" /></div></section>
      </div></div>
  </>;
}

function Field({ label, value, type = "text" }: { label: string; value: string; type?: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input type={type} defaultValue={value} className="w-full rounded-lg border border-slate-300 px-3.5 py-3 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>; }
function SecurityRow({ title, detail, action }: { title: string; detail: string; action: string }) { return <div className="flex flex-col justify-between gap-3 px-6 py-5 sm:flex-row sm:items-center"><div><p className="font-semibold text-slate-900">{title}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></div><button className="w-fit rounded-lg border border-slate-300 px-3.5 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">{action}</button></div>; }
