import { Download, FileClock, Filter, Search, ShieldAlert } from "lucide-react";
import AdminPageHeader from "../../../components/admin/AdminPageHeader";

const logs = [
  { time: "26 Jul 2026, 14:32", actor: "System Administrator", event: "Role assigned", target: "Godwin Malinde", source: "192.168.1.24", severity: "Info" },
  { time: "26 Jul 2026, 13:48", actor: "jane.namusoke@busitema.ac.ug", event: "Employee record updated", target: "BU-CD-001", source: "192.168.1.42", severity: "Info" },
  { time: "26 Jul 2026, 12:17", actor: "Unknown account", event: "Failed sign-in attempt", target: "admin@busitema.ac.ug", source: "10.0.0.18", severity: "Warning" },
  { time: "26 Jul 2026, 10:05", actor: "System Administrator", event: "Account deactivated", target: "Former employee", source: "192.168.1.24", severity: "Important" },
  { time: "25 Jul 2026, 16:22", actor: "Automated system", event: "Database health check", target: "Primary database", source: "Local server", severity: "Success" },
];

export default function AdminAuditLogsPage() {
  return <><AdminPageHeader eyebrow="Security & Accountability" title="Audit Logs" description="Review access, administrative changes and important system events. Audit records are read-only and retained for accountability." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><Download size={18} /> Export audit report</button>} />
    <article className="mb-6 flex gap-3 rounded-xl border border-blue-200 bg-blue-50 p-5"><ShieldAlert className="shrink-0 text-blue-600" size={22} /><div><h2 className="font-bold text-blue-900">Protected audit history</h2><p className="mt-1 text-sm leading-6 text-blue-800">System events are recorded with the responsible user, timestamp, action and source. Administrators may inspect and export records but cannot edit them.</p></div></article>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full lg:max-w-sm"><Search size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" placeholder="Search actor, event or target..." className="w-full rounded-lg border border-slate-300 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><div className="flex flex-wrap gap-3"><input type="date" className="rounded-lg border border-slate-300 px-3 py-2.5 text-sm text-slate-700" /><select className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm text-slate-700"><option>All event types</option><option>Authentication</option><option>Access changes</option><option>Record changes</option><option>System events</option></select><button className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2.5 text-sm font-semibold text-slate-700"><Filter size={17} /> Filters</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-250 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Date & time</th><th className="px-6 py-4">Actor</th><th className="px-6 py-4">Event</th><th className="px-6 py-4">Target</th><th className="px-6 py-4">Source</th><th className="px-6 py-4">Level</th></tr></thead><tbody className="divide-y divide-slate-100">{logs.map((log) => <tr key={`${log.time}-${log.event}`} className="hover:bg-slate-50"><td className="whitespace-nowrap px-6 py-4 text-slate-600"><span className="inline-flex items-center gap-2"><FileClock size={16} className="text-slate-400" />{log.time}</span></td><td className="px-6 py-4 font-semibold text-slate-900">{log.actor}</td><td className="px-6 py-4 text-slate-700">{log.event}</td><td className="px-6 py-4 text-slate-600">{log.target}</td><td className="px-6 py-4 font-mono text-xs text-slate-500">{log.source}</td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${log.severity === "Warning" ? "bg-amber-100 text-amber-700" : log.severity === "Important" ? "bg-red-100 text-red-700" : log.severity === "Success" ? "bg-emerald-100 text-emerald-700" : "bg-blue-100 text-blue-700"}`}>{log.severity}</span></td></tr>)}</tbody></table></div></section>
  </>;
}
