import { BellRing, Database, LockKeyhole, Save, Settings2 } from "lucide-react";
import AdminPageHeader from "../../../components/admin/AdminPageHeader";

export default function AdminSettingsPage() {
  return <><AdminPageHeader eyebrow="Configuration" title="System Settings" description="Configure institution-wide behavior, account security, notifications and data-management controls." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><Save size={18} /> Save settings</button>} />
    <div className="grid gap-6 xl:grid-cols-[230px_1fr]"><aside className="h-fit rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><SettingsLink icon={Settings2} label="General settings" active /><SettingsLink icon={LockKeyhole} label="Authentication" /><SettingsLink icon={BellRing} label="Notifications" /><SettingsLink icon={Database} label="Data & retention" /></aside>
      <div className="space-y-6"><SettingsSection title="General settings" description="Basic institutional information displayed across the system."><div className="grid gap-5 md:grid-cols-2"><Field label="System name" value="Timesheet & Performance Management System" /><Field label="Institution name" value="Busitema University" /><Field label="Default timezone" value="Africa/Kampala (UTC+3)" /><Field label="Support email" value="ictsupport@busitema.ac.ug" /></div></SettingsSection>
        <SettingsSection title="Authentication policy" description="Security requirements applied to user accounts."><div className="grid gap-5 md:grid-cols-2"><Field label="Minimum password length" value="12 characters" /><Field label="Session timeout" value="30 minutes" /><Toggle label="Require multi-factor authentication for administrators" checked /><Toggle label="Lock account after five failed sign-in attempts" checked /><Toggle label="Allow users to remain signed in" /><Toggle label="Notify administrators about suspicious sign-ins" checked /></div></SettingsSection>
        <SettingsSection title="System controls" description="Operational settings that protect records and availability."><div className="grid gap-4 md:grid-cols-2"><Toggle label="Record administrative audit events" checked /><Toggle label="Enable scheduled database backups" checked /><Toggle label="Allow CSV and Excel report exports" checked /><Toggle label="Place system in maintenance mode" /></div></SettingsSection>
      </div></div>
  </>;
}

function SettingsLink({ icon: Icon, label, active = false }: { icon: React.ElementType; label: string; active?: boolean }) { return <button className={`flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm font-semibold ${active ? "bg-blue-50 text-blue-700" : "text-slate-600 hover:bg-slate-50"}`}><Icon size={18} />{label}</button>; }
function SettingsSection({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div><div className="p-6">{children}</div></section>; }
function Field({ label, value }: { label: string; value: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input defaultValue={value} className="w-full rounded-lg border border-slate-300 px-3.5 py-3 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>; }
function Toggle({ label, checked = false }: { label: string; checked?: boolean }) { return <label className="flex items-center justify-between gap-4 rounded-lg border border-slate-200 p-4"><span className="text-sm font-medium text-slate-700">{label}</span><input type="checkbox" defaultChecked={checked} className="h-5 w-5 rounded border-slate-300 text-blue-600" /></label>; }
