import { BarChart3, Building2, CalendarDays, Download, FileSpreadsheet, FileText, PieChart, UsersRound } from "lucide-react";
import HrPageHeader from "../../../components/hr/HrPageHeader";

const reports = [
  { title: "Workforce summary", description: "Employees by department, campus, employment type and status.", icon: UsersRound, updated: "Updated today" },
  { title: "Timesheet compliance", description: "Submission and approval rates across organizational units.", icon: CalendarDays, updated: "Updated 15 minutes ago" },
  { title: "Institutional performance", description: "Performance distribution, trends and classification bands.", icon: BarChart3, updated: "Updated today" },
  { title: "Supervisor coverage", description: "Reporting-line assignments and employees without supervisors.", icon: PieChart, updated: "Updated today" },
  { title: "Department comparison", description: "Compare hours, completion and performance by department.", icon: Building2, updated: "Updated 1 hour ago" },
  { title: "Employee master list", description: "Complete approved employee directory for administrative use.", icon: FileSpreadsheet, updated: "Updated today" },
];

export default function HrReportsPage() {
  return <><HrPageHeader eyebrow="HR Analytics" title="Human Resources Reports" description="Generate workforce, compliance and performance reports for authorized institutional decision-making." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><FileText size={18} /> Build custom report</button>} />
    <section className="mb-7 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-4"><label><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Period</span><select className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>July 2026</option><option>June 2026</option><option>2026 Year to date</option></select></label><label><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Department</span><select className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>All departments</option><option>University Library</option><option>ICT Directorate</option></select></label><label><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Campus</span><select className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>All campuses</option><option>Busitema Campus</option><option>Main Administration</option></select></label><div className="flex items-end"><button className="w-full rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Apply report filters</button></div></div></section>
    <section className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{reports.map((report) => { const Icon = report.icon; return <article key={report.title} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><Icon size={22} /></div><span className="text-xs text-slate-400">{report.updated}</span></div><h2 className="mt-5 font-bold text-slate-900">{report.title}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{report.description}</p><div className="mt-5 flex gap-3 border-t border-slate-100 pt-5"><button className="flex-1 rounded-lg bg-blue-600 px-3 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">View report</button><button aria-label={`Download ${report.title}`} className="rounded-lg border border-slate-300 p-2.5 text-slate-600 hover:bg-slate-50"><Download size={18} /></button></div></article>; })}</section>
  </>;
}
