import { AlertTriangle, CheckCircle2, Edit3, Plus, Target } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

const targets = [
  { code: "TGT-01", name: "Institutional performance score", owner: "Planning Directorate", target: "85%", actual: 82, status: "Watch" },
  { code: "TGT-02", name: "Timesheet reporting compliance", owner: "Human Resources", target: "95%", actual: 86.5, status: "At risk" },
  { code: "TGT-03", name: "Task completion rate", owner: "All Departments", target: "90%", actual: 88, status: "Watch" },
  { code: "TGT-04", name: "Supervisor approval turnaround", owner: "Department Heads", target: "90%", actual: 93, status: "On track" },
  { code: "TGT-05", name: "Complete performance records", owner: "M&E Unit", target: "98%", actual: 95.3, status: "Watch" },
];

export default function MeTargetsPage() {
  return <><MePageHeader eyebrow="Results Framework" title="Institutional Targets" description="Set performance expectations and monitor actual achievement against approved institutional and departmental targets." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><Plus size={18} /> Add target</button>} />
    <section className="grid gap-5 md:grid-cols-3"><Summary icon={Target} value="25" label="Active targets" detail="Institutional and departmental" tone="blue" /><Summary icon={CheckCircle2} value="19" label="On track" detail="76% target achievement" tone="emerald" /><Summary icon={AlertTriangle} value="6" label="Need attention" detail="Five watch, one at risk" tone="amber" /></section>
    <section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-lg font-bold text-slate-900">Target performance register</h2><p className="mt-1 text-sm text-slate-500">Current actuals compared with approved reporting-period expectations</p></div><div className="overflow-x-auto"><table className="w-full min-w-250 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Target</th><th className="px-6 py-4">Owner</th><th className="px-6 py-4">Expected</th><th className="px-6 py-4">Actual</th><th className="px-6 py-4">Progress</th><th className="px-6 py-4">Status</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{targets.map((item) => <tr key={item.code} className="hover:bg-slate-50"><td className="px-6 py-4"><p className="font-semibold text-slate-900">{item.name}</p><p className="mt-1 font-mono text-xs text-slate-400">{item.code}</p></td><td className="px-6 py-4 text-slate-600">{item.owner}</td><td className="px-6 py-4 font-bold text-slate-700">{item.target}</td><td className="px-6 py-4 font-bold text-slate-900">{item.actual}%</td><td className="min-w-45 px-6 py-4"><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.status === "On track" ? "bg-emerald-500" : item.status === "At risk" ? "bg-red-500" : "bg-amber-500"}`} style={{ width: `${Math.min(item.actual, 100)}%` }} /></div></td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.status === "On track" ? "bg-emerald-100 text-emerald-700" : item.status === "At risk" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}`}>{item.status}</span></td><td className="px-6 py-4 text-right"><button aria-label={`Edit ${item.name}`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Edit3 size={18} /></button></td></tr>)}</tbody></table></div></section>
  </>;
}

function Summary({ icon: Icon, value, label, detail, tone }: { icon: React.ElementType; value: string; label: string; detail: string; tone: "blue" | "emerald" | "amber" }) { const colours = { blue: "bg-blue-50 text-blue-600", emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600" }; return <article className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`rounded-xl p-3 ${colours[tone]}`}><Icon size={23} /></div><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></article>; }
