import { Building2, MapPin, MoreHorizontal, Plus, UsersRound } from "lucide-react";
import AdminPageHeader from "../../../components/admin/AdminPageHeader";

const departments = [
  { code: "LIB", name: "University Library", campus: "Busitema Campus", employees: 34, head: "Faculty Librarian" },
  { code: "ICT", name: "ICT Directorate", campus: "Main Administration", employees: 22, head: "Director ICT" },
  { code: "HR", name: "Human Resources", campus: "Main Administration", employees: 12, head: "Director Human Resources" },
  { code: "PLAN", name: "Planning Directorate", campus: "Main Administration", employees: 16, head: "Director Planning" },
];

export default function AdminOrganizationPage() {
  return <><AdminPageHeader eyebrow="Institutional Structure" title="Organization Management" description="Maintain campuses, departments and reporting structures used to scope employee and supervisor access." actions={<><button className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><MapPin size={18} /> Manage campuses</button><button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><Plus size={18} /> Add department</button></>} />
    <section className="grid gap-5 md:grid-cols-3"><Summary icon={Building2} label="Departments" value="12" detail="Across the institution" /><Summary icon={MapPin} label="Campuses" value="7" detail="Active operating locations" /><Summary icon={UsersRound} label="Assigned employees" value="148" detail="All employee records mapped" /></section>
    <section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-lg font-bold text-slate-900">Departments and directorates</h2><p className="mt-1 text-sm text-slate-500">Organizational units currently configured in the system</p></div><div className="overflow-x-auto"><table className="w-full min-w-200 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Department</th><th className="px-6 py-4">Code</th><th className="px-6 py-4">Campus</th><th className="px-6 py-4">Head / Supervisor</th><th className="px-6 py-4">Employees</th><th className="px-6 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{departments.map((department) => <tr key={department.code} className="hover:bg-slate-50"><td className="px-6 py-4 font-semibold text-slate-900">{department.name}</td><td className="px-6 py-4"><span className="rounded-md bg-slate-100 px-2.5 py-1 font-mono text-xs font-bold text-slate-600">{department.code}</span></td><td className="px-6 py-4 text-slate-600">{department.campus}</td><td className="px-6 py-4 text-slate-600">{department.head}</td><td className="px-6 py-4 font-semibold text-slate-700">{department.employees}</td><td className="px-6 py-4 text-right"><button aria-label={`Manage ${department.name}`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><MoreHorizontal size={19} /></button></td></tr>)}</tbody></table></div></section>
  </>;
}

function Summary({ icon: Icon, label, value, detail }: { icon: React.ElementType; label: string; value: string; detail: string }) { return <article className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><Icon size={23} /></div><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></article>; }
