import { AlertTriangle, CheckCircle2, ClipboardCheck, Clock3, Download } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

const compliance = [
  { department: "Human Resources", expected: 12, submitted: 12, approved: 12, rate: 100, status: "Complete" },
  { department: "ICT Directorate", expected: 22, submitted: 21, approved: 20, rate: 91, status: "Nearly complete" },
  { department: "University Library", expected: 34, submitted: 30, approved: 28, rate: 82, status: "Follow up" },
  { department: "Finance Department", expected: 25, submitted: 22, approved: 20, rate: 80, status: "Follow up" },
  { department: "Planning Directorate", expected: 16, submitted: 13, approved: 11, rate: 69, status: "Escalate" },
];

export default function MeCompliancePage() {
  return <><MePageHeader eyebrow="Reporting Oversight" title="Reporting Compliance" description="Monitor whether employee records are submitted, reviewed and ready for inclusion in institutional performance reports." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><Download size={18} /> Export compliance report</button>} />
    <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={ClipboardCheck} value="148" label="Expected records" detail="Current reporting period" tone="blue" /><Summary icon={CheckCircle2} value="128" label="Report-ready" detail="86.5% compliance" tone="emerald" /><Summary icon={Clock3} value="13" label="Awaiting approval" detail="Submitted to supervisors" tone="amber" /><Summary icon={AlertTriangle} value="7" label="Not submitted" detail="Require follow-up" tone="red" /></section>
    <section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-lg font-bold text-slate-900">Compliance by department</h2><p className="mt-1 text-sm text-slate-500">Approved records compared with expected employee submissions</p></div><div className="overflow-x-auto"><table className="w-full min-w-225 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Department</th><th className="px-6 py-4">Expected</th><th className="px-6 py-4">Submitted</th><th className="px-6 py-4">Approved</th><th className="px-6 py-4">Compliance rate</th><th className="px-6 py-4">Action status</th></tr></thead><tbody className="divide-y divide-slate-100">{compliance.map((item) => <tr key={item.department} className="hover:bg-slate-50"><td className="px-6 py-4 font-semibold text-slate-900">{item.department}</td><td className="px-6 py-4 text-slate-600">{item.expected}</td><td className="px-6 py-4 text-slate-600">{item.submitted}</td><td className="px-6 py-4 font-semibold text-slate-700">{item.approved}</td><td className="min-w-55 px-6 py-4"><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Progress</span><b>{item.rate}%</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${item.rate >= 95 ? "bg-emerald-500" : item.rate >= 80 ? "bg-amber-500" : "bg-red-500"}`} style={{ width: `${item.rate}%` }} /></div></td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.status === "Complete" ? "bg-emerald-100 text-emerald-700" : item.status === "Escalate" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}`}>{item.status}</span></td></tr>)}</tbody></table></div></section>
  </>;
}

function Summary({ icon: Icon, value, label, detail, tone }: { icon: React.ElementType; value: string; label: string; detail: string; tone: "blue" | "emerald" | "amber" | "red" }) { const colours = { blue: "bg-blue-50 text-blue-600", emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", red: "bg-red-50 text-red-600" }; return <article className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`rounded-xl p-3 ${colours[tone]}`}><Icon size={23} /></div><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></article>; }
