import Link from "next/link";
import { AlertCircle, ArrowRight, BarChart3, Building2, CalendarClock, FileText, Network, UserCheck, UserPlus, UsersRound } from "lucide-react";
import HrPageHeader from "../../../components/hr/HrPageHeader";
import HrStatCard from "../../../components/hr/HrStatCard";

const workforce = [
  { department: "University Library", employees: 34, supervisors: 4, completion: 88 },
  { department: "ICT Directorate", employees: 22, supervisors: 3, completion: 92 },
  { department: "Human Resources", employees: 12, supervisors: 2, completion: 100 },
  { department: "Planning Directorate", employees: 16, supervisors: 2, completion: 81 },
];

const attentionItems = [
  { title: "Employees without supervisors", count: 4, detail: "Reporting lines require assignment", icon: Network, tone: "bg-red-50 text-red-600", href: "/hr/reporting-lines" },
  { title: "Incomplete employee records", count: 7, detail: "Missing campus or contact information", icon: AlertCircle, tone: "bg-amber-50 text-amber-600", href: "/hr/employees" },
  { title: "Performance period closing", count: 12, detail: "Days remaining in the July cycle", icon: CalendarClock, tone: "bg-blue-50 text-blue-600", href: "/hr/performance" },
];

export default function HrDashboardPage() {
  return <><HrPageHeader eyebrow="Human Resources Overview" title="People & Performance Dashboard" description="Maintain reliable workforce records, reporting relationships and institution-wide performance administration." actions={<><Link href="/hr/reports" className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><FileText size={18} /> View HR reports</Link><Link href="/hr/employees" className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><UserPlus size={18} /> Add employee record</Link></>} />
    <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><HrStatCard title="Total employees" value="148" description="136 active employee records" icon={UsersRound} /><HrStatCard title="Departments" value="12" description="Across seven campuses" icon={Building2} tone="emerald" /><HrStatCard title="Assigned supervisors" value="144" description="97% reporting-line coverage" icon={UserCheck} tone="emerald" /><HrStatCard title="Average performance" value="82%" description="Current institutional average" icon={BarChart3} tone="blue" /></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><article className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-6 py-5"><div><h2 className="text-lg font-bold text-slate-900">Workforce by department</h2><p className="mt-1 text-sm text-slate-500">Employee distribution and timesheet completion this month</p></div><Link href="/hr/departments" className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:text-blue-700">View departments <ArrowRight size={16} /></Link></div><div className="overflow-x-auto"><table className="w-full min-w-175 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Department</th><th className="px-6 py-4">Employees</th><th className="px-6 py-4">Supervisors</th><th className="px-6 py-4">Completion</th></tr></thead><tbody className="divide-y divide-slate-100">{workforce.map((item) => <tr key={item.department} className="hover:bg-slate-50"><td className="px-6 py-4 font-semibold text-slate-900">{item.department}</td><td className="px-6 py-4 font-medium text-slate-700">{item.employees}</td><td className="px-6 py-4 text-slate-600">{item.supervisors}</td><td className="min-w-55 px-6 py-4"><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Timesheets submitted</span><b className="text-slate-700">{item.completion}%</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${item.completion}%` }} /></div></td></tr>)}</tbody></table></div></article>
      <article className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-lg font-bold text-slate-900">Requires attention</h2><p className="mt-1 text-sm text-slate-500">Workforce records needing HR action</p></div><div className="divide-y divide-slate-100">{attentionItems.map((item) => { const Icon = item.icon; return <div key={item.title} className="p-5"><div className="flex gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${item.tone}`}><Icon size={20} /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="text-sm font-semibold text-slate-900">{item.title}</p><span className="text-xl font-bold text-slate-900">{item.count}</span></div><p className="mt-1 text-xs text-slate-500">{item.detail}</p><Link href={item.href} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-blue-600">Review records <ArrowRight size={14} /></Link></div></div></div>; })}</div></article></section>
    <section className="mt-7 grid gap-6 md:grid-cols-3"><Insight title="Active workforce" value="91.9%" description="136 of 148 employee records are currently active." /><Insight title="Supervisor coverage" value="97.3%" description="Four employees still require a reporting-line assignment." /><Insight title="Timesheet compliance" value="86.5%" description="Institutional submission rate for the current period." /></section>
  </>;
}

function Insight({ title, value, description }: { title: string; value: string; description: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-medium text-slate-500">{title}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p><p className="mt-3 text-sm leading-6 text-slate-500">{description}</p></article>; }
