import { Activity, CalendarDays, Download, Filter, TrendingDown, TrendingUp } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

const periods = [
  { period: "July 2026", score: 82, taskCompletion: 88, timesheets: 86.5, approvals: 93, change: "+2.6%" },
  { period: "June 2026", score: 79.4, taskCompletion: 84, timesheets: 83, approvals: 91, change: "+1.1%" },
  { period: "May 2026", score: 78.3, taskCompletion: 82, timesheets: 81, approvals: 90, change: "-0.7%" },
  { period: "April 2026", score: 79, taskCompletion: 83, timesheets: 82, approvals: 91, change: "+1.8%" },
];

export default function MeMonitoringPage() {
  return <><MePageHeader eyebrow="Performance Oversight" title="Performance Monitoring" description="Monitor institutional results over time and identify patterns that require validation, management attention or corrective action." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"><Download size={18} /> Export monitoring brief</button>} />
    <section className="mb-7 grid gap-5 md:grid-cols-4"><Metric label="Current score" value="82%" note="Target: 85%" positive /><Metric label="Quarter average" value="79.9%" note="Up 1.8 points" positive /><Metric label="Strongest indicator" value="93%" note="Supervisor approval" positive /><Metric label="Weakest indicator" value="86.5%" note="Reporting compliance" /></section>
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="text-lg font-bold text-slate-900">Performance trend</h2><p className="mt-1 text-sm text-slate-500">Institutional indicator results by reporting period</p></div><div className="flex flex-wrap gap-3"><select className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>2026</option><option>2025</option></select><select className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>Institution-wide</option><option>By department</option><option>By campus</option></select><button className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-3 py-2.5 text-sm font-semibold text-slate-700"><Filter size={17} /> Apply</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-225 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Period</th><th className="px-6 py-4">Overall score</th><th className="px-6 py-4">Task completion</th><th className="px-6 py-4">Timesheet submission</th><th className="px-6 py-4">Approval rate</th><th className="px-6 py-4">Change</th></tr></thead><tbody className="divide-y divide-slate-100">{periods.map((period) => <tr key={period.period} className="hover:bg-slate-50"><td className="px-6 py-4"><span className="inline-flex items-center gap-2 font-semibold text-slate-900"><CalendarDays size={17} className="text-slate-400" />{period.period}</span></td><td className="px-6 py-4 text-lg font-bold text-slate-900">{period.score}%</td><td className="px-6 py-4 font-medium text-slate-700">{period.taskCompletion}%</td><td className="px-6 py-4 font-medium text-slate-700">{period.timesheets}%</td><td className="px-6 py-4 font-medium text-slate-700">{period.approvals}%</td><td className={`px-6 py-4 font-semibold ${period.change.startsWith("+") ? "text-emerald-600" : "text-red-600"}`}><span className="inline-flex items-center gap-1">{period.change.startsWith("+") ? <TrendingUp size={16} /> : <TrendingDown size={16} />}{period.change}</span></td></tr>)}</tbody></table></div></section>
    <section className="mt-6 grid gap-6 md:grid-cols-2"><Finding title="Positive movement" description="Task completion has improved for three consecutive reporting periods, rising from 82% in May to 88% in July." tone="border-emerald-200 bg-emerald-50 text-emerald-900" /><Finding title="Reporting gap" description="Timesheet compliance remains below the 95% institutional target and requires department-level follow-up." tone="border-amber-200 bg-amber-50 text-amber-900" /></section>
  </>;
}

function Metric({ label, value, note, positive }: { label: string; value: string; note: string; positive?: boolean }) { return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><Activity size={20} className={positive ? "text-emerald-600" : "text-amber-600"} /><span className={`h-2.5 w-2.5 rounded-full ${positive ? "bg-emerald-500" : "bg-amber-500"}`} /></div><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-2 text-xs text-slate-500">{note}</p></article>; }
function Finding({ title, description, tone }: { title: string; description: string; tone: string }) { return <article className={`rounded-xl border p-5 ${tone}`}><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-6 opacity-90">{description}</p></article>; }
