import { KeyRound, Mail, MapPin, Phone, Save, ShieldCheck, UserRound } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

export default function MeProfilePage() {
  return <><MePageHeader eyebrow="My Account" title="M&E Officer Profile" description="Review your professional information and protected access to institutional performance data." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Save size={18} /> Save profile</button>} />
    <div className="grid gap-6 xl:grid-cols-[330px_1fr]"><aside className="h-fit rounded-xl border border-slate-200 bg-white p-6 text-center shadow-sm"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-blue-100 text-3xl font-bold text-blue-700">MO</div><h2 className="mt-4 text-xl font-bold text-slate-900">M&amp;E Officer</h2><p className="mt-1 text-sm text-slate-500">Planning Directorate</p><span className="mt-4 inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1.5 text-xs font-semibold text-emerald-700"><ShieldCheck size={15} /> Monitoring &amp; Evaluation</span><div className="mt-6 space-y-3 border-t border-slate-100 pt-6 text-left text-sm text-slate-600"><p className="flex items-center gap-3"><Mail size={17} className="text-slate-400" /> me.officer@busitema.ac.ug</p><p className="flex items-center gap-3"><Phone size={17} className="text-slate-400" /> +256 700 000 020</p><p className="flex items-center gap-3"><MapPin size={17} className="text-slate-400" /> Main Administration</p></div></aside>
      <div className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="flex items-center gap-2 text-lg font-bold text-slate-900"><UserRound size={20} className="text-blue-600" /> Personal information</h2><p className="mt-1 text-sm text-slate-500">Information associated with your employee and M&E access record</p></div><div className="grid gap-5 p-6 md:grid-cols-2"><Field label="First name" value="Monitoring" /><Field label="Last name" value="Officer" /><Field label="Employee number" value="BU-ME-020" /><Field label="Work email" value="me.officer@busitema.ac.ug" type="email" /><Field label="Phone number" value="+256 700 000 020" /><Field label="Job title" value="Monitoring & Evaluation Officer" /><Field label="Department" value="Planning Directorate" /><Field label="Campus / station" value="Main Administration" /></div></section><section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="flex items-center gap-2 text-lg font-bold text-slate-900"><KeyRound size={20} className="text-blue-600" /> Account security</h2><p className="mt-1 text-sm text-slate-500">Password, sessions and performance-data access</p></div><div className="divide-y divide-slate-100"><SecurityRow title="Password" detail="Last changed 38 days ago" action="Change password" /><SecurityRow title="Multi-factor authentication" detail="Enabled for institutional reporting access" action="Manage MFA" /><SecurityRow title="Active sessions" detail="One active session on this device" action="Review sessions" /></div></section></div></div>
  </>;
}

function Field({ label, value, type = "text" }: { label: string; value: string; type?: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold text-slate-700">{label}</span><input type={type} defaultValue={value} className="w-full rounded-lg border border-slate-300 px-3.5 py-3 text-sm text-slate-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></label>; }
function SecurityRow({ title, detail, action }: { title: string; detail: string; action: string }) { return <div className="flex flex-col justify-between gap-3 px-6 py-5 sm:flex-row sm:items-center"><div><p className="font-semibold text-slate-900">{title}</p><p className="mt-1 text-sm text-slate-500">{detail}</p></div><button className="w-fit rounded-lg border border-slate-300 px-3.5 py-2 text-sm font-semibold text-slate-700">{action}</button></div>; }
