import { Building2, Download, Filter, TrendingDown, TrendingUp } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

const departments = [
  { rank: 1, name: "ICT Directorate", employees: 22, score: 89, tasks: 94, compliance: 92, trend: 4.2, status: "On target" },
  { rank: 2, name: "Human Resources", employees: 12, score: 86, tasks: 88, compliance: 100, trend: 2.1, status: "On target" },
  { rank: 3, name: "University Library", employees: 34, score: 82, tasks: 90, compliance: 88, trend: 1.5, status: "Watch" },
  { rank: 4, name: "Finance Department", employees: 25, score: 78, tasks: 84, compliance: 84, trend: -1.8, status: "At risk" },
  { rank: 5, name: "Planning Directorate", employees: 16, score: 75, tasks: 80, compliance: 81, trend: -3.1, status: "At risk" },
];

export default function MeDepartmentsPage() {
  return <><MePageHeader eyebrow="Comparative Analysis" title="Department Performance Comparison" description="Compare results across organizational units while preserving the context of workforce size, reporting compliance and approved targets." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><Download size={18} /> Export comparison</button>} />
    <section className="mb-7 flex flex-wrap gap-3 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><select className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>July 2026</option><option>June 2026</option></select><select className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>All campuses</option><option>Busitema Campus</option><option>Main Administration</option></select><select className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option>Overall performance</option><option>Task completion</option><option>Reporting compliance</option></select><button className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Filter size={17} /> Apply comparison</button></section>
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-lg font-bold text-slate-900">Department ranking</h2><p className="mt-1 text-sm text-slate-500">Performance is compared with the institutional target of 85%</p></div><div className="overflow-x-auto"><table className="w-full min-w-250 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Rank</th><th className="px-6 py-4">Department</th><th className="px-6 py-4">Employees</th><th className="px-6 py-4">Overall score</th><th className="px-6 py-4">Task completion</th><th className="px-6 py-4">Compliance</th><th className="px-6 py-4">Trend</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{departments.map((department) => <tr key={department.name} className="hover:bg-slate-50"><td className="px-6 py-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 font-bold text-slate-700">{department.rank}</span></td><td className="px-6 py-4"><span className="inline-flex items-center gap-2 font-semibold text-slate-900"><Building2 size={17} className="text-blue-600" />{department.name}</span></td><td className="px-6 py-4 text-slate-600">{department.employees}</td><td className="px-6 py-4 text-lg font-bold text-slate-900">{department.score}%</td><td className="px-6 py-4 font-medium text-slate-700">{department.tasks}%</td><td className="px-6 py-4 font-medium text-slate-700">{department.compliance}%</td><td className={`px-6 py-4 font-semibold ${department.trend > 0 ? "text-emerald-600" : "text-red-600"}`}><span className="inline-flex items-center gap-1">{department.trend > 0 ? <TrendingUp size={16} /> : <TrendingDown size={16} />}{department.trend > 0 ? "+" : ""}{department.trend}%</span></td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${department.status === "On target" ? "bg-emerald-100 text-emerald-700" : department.status === "Watch" ? "bg-blue-100 text-blue-700" : "bg-red-100 text-red-700"}`}>{department.status}</span></td></tr>)}</tbody></table></div></section>
  </>;
}
