import { AlertTriangle, CheckCircle2, DatabaseZap, RefreshCw, Search, ShieldCheck } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

const exceptions = [
  { id: "DQ-2026-041", issue: "Performance score missing", record: "BU-CD-018 · July 2026", owner: "University Library", severity: "High", status: "Open" },
  { id: "DQ-2026-040", issue: "Approved timesheet has zero hours", record: "BU-FIN-009 · July 2026", owner: "Finance Department", severity: "High", status: "Investigating" },
  { id: "DQ-2026-039", issue: "Employee has no department mapping", record: "BU-RA-007", owner: "Human Resources", severity: "Medium", status: "Open" },
  { id: "DQ-2026-038", issue: "Indicator weights do not match period", record: "June 2026 performance cycle", owner: "M&E Unit", severity: "Medium", status: "Resolved" },
  { id: "DQ-2026-037", issue: "Duplicate activity reference", record: "Activity ACT-1382", owner: "ICT Directorate", severity: "Low", status: "Resolved" },
];

export default function MeDataQualityPage() {
  return <><MePageHeader eyebrow="Evidence Integrity" title="Data Quality Review" description="Validate completeness, consistency and calculation integrity before information is included in institutional performance reporting." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><RefreshCw size={18} /> Run validation checks</button>} />
    <section className="grid gap-5 md:grid-cols-4"><Quality icon={DatabaseZap} value="95.3%" label="Quality score" tone="blue" /><Quality icon={AlertTriangle} value="7" label="Open exceptions" tone="amber" /><Quality icon={ShieldCheck} value="3" label="High priority" tone="red" /><Quality icon={CheckCircle2} value="24" label="Resolved this month" tone="emerald" /></section>
    <section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-bold text-slate-900">Validation exceptions</h2><p className="mt-1 text-sm text-slate-500">Potential issues identified by automated and manual review</p></div><div className="relative"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" placeholder="Search exceptions..." className="rounded-lg border border-slate-300 py-2 pl-9 pr-3 text-sm outline-none focus:border-blue-500" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-250 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Reference</th><th className="px-6 py-4">Quality issue</th><th className="px-6 py-4">Affected record</th><th className="px-6 py-4">Responsible unit</th><th className="px-6 py-4">Severity</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{exceptions.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-6 py-4 font-mono text-xs font-bold text-slate-500">{item.id}</td><td className="px-6 py-4 font-semibold text-slate-900">{item.issue}</td><td className="px-6 py-4 text-slate-600">{item.record}</td><td className="px-6 py-4 text-slate-600">{item.owner}</td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${item.severity === "High" ? "bg-red-100 text-red-700" : item.severity === "Medium" ? "bg-amber-100 text-amber-700" : "bg-slate-200 text-slate-600"}`}>{item.severity}</span></td><td className="px-6 py-4 text-slate-600">{item.status}</td><td className="px-6 py-4"><button className="font-semibold text-blue-600">Review</button></td></tr>)}</tbody></table></div></section>
  </>;
}

function Quality({ icon: Icon, value, label, tone }: { icon: React.ElementType; value: string; label: string; tone: "blue" | "emerald" | "amber" | "red" }) { const colours = { blue: "bg-blue-50 text-blue-600", emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", red: "bg-red-50 text-red-600" }; return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`w-fit rounded-xl p-3 ${colours[tone]}`}><Icon size={22} /></div><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></article>; }
