import { CheckCircle2, Edit3, Plus, Scale, SlidersHorizontal } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

const indicators = [
  { code: "KPI-01", name: "Task completion rate", source: "Approved tasks", frequency: "Monthly", weight: 50, status: "Active" },
  { code: "KPI-02", name: "Timesheet submission rate", source: "Submitted timesheets", frequency: "Monthly", weight: 30, status: "Active" },
  { code: "KPI-03", name: "Supervisor approval rate", source: "Reviewed timesheets", frequency: "Monthly", weight: 20, status: "Active" },
  { code: "KPI-04", name: "Output achievement rate", source: "Activity outputs", frequency: "Quarterly", weight: 0, status: "Draft" },
];

export default function MeIndicatorsPage() {
  return <><MePageHeader eyebrow="Measurement Framework" title="Performance Indicators" description="Define measurable indicators, data sources, reporting frequency and approved weights used for institutional performance monitoring." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><Plus size={18} /> Add indicator</button>} />
    <section className="grid gap-5 md:grid-cols-3"><Summary icon={SlidersHorizontal} value="4" label="Configured indicators" detail="Three active, one draft" /><Summary icon={Scale} value="100%" label="Active total weight" detail="Weight validation passed" /><Summary icon={CheckCircle2} value="3" label="Verified data sources" detail="All active indicators mapped" /></section>
    <section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="text-lg font-bold text-slate-900">Indicator register</h2><p className="mt-1 text-sm text-slate-500">Version-controlled definitions for institutional measurement</p></div><div className="overflow-x-auto"><table className="w-full min-w-225 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Code</th><th className="px-6 py-4">Indicator</th><th className="px-6 py-4">Data source</th><th className="px-6 py-4">Frequency</th><th className="px-6 py-4">Weight</th><th className="px-6 py-4">Status</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{indicators.map((indicator) => <tr key={indicator.code} className="hover:bg-slate-50"><td className="px-6 py-4 font-mono text-xs font-bold text-slate-600">{indicator.code}</td><td className="px-6 py-4 font-semibold text-slate-900">{indicator.name}</td><td className="px-6 py-4 text-slate-600">{indicator.source}</td><td className="px-6 py-4 text-slate-600">{indicator.frequency}</td><td className="px-6 py-4 font-bold text-slate-700">{indicator.weight}%</td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${indicator.status === "Active" ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-600"}`}>{indicator.status}</span></td><td className="px-6 py-4 text-right"><button aria-label={`Edit ${indicator.name}`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Edit3 size={18} /></button></td></tr>)}</tbody></table></div></section>
    <article className="mt-6 rounded-xl border border-blue-200 bg-blue-50 p-5"><h3 className="font-bold text-blue-900">Indicator governance</h3><p className="mt-1 text-sm leading-6 text-blue-800">Changes to active indicator definitions and weights should create a new version and take effect in a future reporting period. Historical performance results must retain the indicator version used when they were calculated.</p></article>
  </>;
}

function Summary({ icon: Icon, value, label, detail }: { icon: React.ElementType; value: string; label: string; detail: string }) { return <article className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><Icon size={23} /></div><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></article>; }
