import { BarChart3, CalendarDays, CheckCircle2, Edit3, Plus, Scale, Target } from "lucide-react";
import HrPageHeader from "../../../components/hr/HrPageHeader";

const indicators = [
  { name: "Task completion", description: "Completed assigned tasks within the review period", weight: 50, owner: "Supervisors" },
  { name: "Timesheet submission", description: "Complete and timely submission of employee timesheets", weight: 30, owner: "System calculated" },
  { name: "Supervisor approval", description: "Quality and acceptance of submitted work records", weight: 20, owner: "Supervisors" },
];

export default function HrPerformancePage() {
  return <><HrPageHeader eyebrow="Performance Administration" title="Performance Setup" description="Manage review periods, institutional indicators and the approved calculation structure used for employee performance." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700"><Plus size={18} /> New review period</button>} />
    <section className="grid gap-5 md:grid-cols-3"><Summary icon={CalendarDays} label="Current period" value="July 2026" detail="Closes 31 July 2026" /><Summary icon={Target} label="Active indicators" value="3" detail="Total weight: 100%" /><Summary icon={CheckCircle2} label="Calculated records" value="128" detail="86.5% of employees" /></section>
    <section className="mt-7 grid gap-6 xl:grid-cols-[1.35fr_1fr]"><article className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-6 py-5"><div><h2 className="text-lg font-bold text-slate-900">Performance indicators</h2><p className="mt-1 text-sm text-slate-500">Approved components of the overall employee score</p></div><button className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><Plus size={16} /> Add indicator</button></div><div className="divide-y divide-slate-100">{indicators.map((indicator) => <div key={indicator.name} className="p-6"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><BarChart3 size={20} /></div><div><h3 className="font-bold text-slate-900">{indicator.name}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{indicator.description}</p></div></div><button aria-label={`Edit ${indicator.name}`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Edit3 size={18} /></button></div><div className="mt-4 flex flex-wrap gap-3 pl-13"><span className="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-700">Weight: {indicator.weight}%</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">Source: {indicator.owner}</span></div></div>)}</div></article>
      <div className="space-y-6"><article className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-50 p-3 text-emerald-600"><Scale size={21} /></div><div><h2 className="font-bold text-slate-900">Weight validation</h2><p className="mt-1 text-sm text-slate-500">Current indicator total</p></div></div><div className="mt-5 flex items-end justify-between"><span className="text-4xl font-bold text-slate-900">100%</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">Valid</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-full rounded-full bg-emerald-500" /></div></article>
        <article className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-6 py-5"><h2 className="font-bold text-slate-900">Classification bands</h2><p className="mt-1 text-sm text-slate-500">Institutional score interpretation</p></div><div className="space-y-3 p-6"><Band label="Excellent" range="90–100%" tone="bg-emerald-500" /><Band label="Very good" range="80–89%" tone="bg-blue-600" /><Band label="Good" range="70–79%" tone="bg-amber-500" /><Band label="Needs attention" range="Below 70%" tone="bg-red-500" /></div></article></div></section>
  </>;
}

function Summary({ icon: Icon, label, value, detail }: { icon: React.ElementType; label: string; value: string; detail: string }) { return <article className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><Icon size={23} /></div><div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></div></article>; }
function Band({ label, range, tone }: { label: string; range: string; tone: string }) { return <div className="flex items-center justify-between rounded-lg border border-slate-200 px-4 py-3"><span className="flex items-center gap-2 text-sm font-semibold text-slate-700"><span className={`h-2.5 w-2.5 rounded-full ${tone}`} />{label}</span><span className="text-xs font-medium text-slate-500">{range}</span></div>; }
