import { AlertTriangle, CheckCircle2, Clock3, Lightbulb, Plus, Target } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

const recommendations = [
  { id: "REC-026", title: "Improve timesheet follow-up in Planning Directorate", finding: "Reporting compliance is 14 points below the institutional target.", owner: "Director Planning", due: "15 Aug 2026", priority: "High", status: "Open" },
  { id: "REC-025", title: "Review Finance task-planning practices", finding: "Task completion declined by 1.8% for the second consecutive period.", owner: "University Bursar", due: "20 Aug 2026", priority: "High", status: "In progress" },
  { id: "REC-024", title: "Document ICT performance practices", finding: "ICT exceeded target and may provide replicable lessons for other units.", owner: "M&E Unit", due: "30 Aug 2026", priority: "Medium", status: "Open" },
  { id: "REC-023", title: "Resolve uncalculated employee records", finding: "Twenty records were excluded from the preliminary institutional score.", owner: "HR & M&E", due: "05 Aug 2026", priority: "High", status: "Completed" },
];

export default function MeRecommendationsPage() {
  return <><MePageHeader eyebrow="Corrective Action" title="M&E Recommendations" description="Translate validated findings into accountable actions with responsible owners, deadlines and follow-up status." actions={<button className="inline-flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={18} /> Add recommendation</button>} />
    <section className="grid gap-5 md:grid-cols-4"><Count icon={Lightbulb} value="14" label="All recommendations" tone="blue" /><Count icon={AlertTriangle} value="5" label="High priority" tone="red" /><Count icon={Clock3} value="6" label="In progress" tone="amber" /><Count icon={CheckCircle2} value="3" label="Completed" tone="emerald" /></section>
    <section className="mt-7 space-y-4">{recommendations.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div className="flex gap-4"><div className="rounded-xl bg-blue-50 p-3 text-blue-600"><Target size={21} /></div><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-bold text-slate-400">{item.id}</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.priority === "High" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}`}>{item.priority} priority</span></div><h2 className="mt-2 font-bold text-slate-900">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-500"><b className="text-slate-700">Finding:</b> {item.finding}</p></div></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-semibold ${item.status === "Completed" ? "bg-emerald-100 text-emerald-700" : item.status === "In progress" ? "bg-blue-100 text-blue-700" : "bg-slate-200 text-slate-600"}`}>{item.status}</span></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-slate-100 pt-4 text-sm"><p className="text-slate-500">Responsible: <b className="text-slate-700">{item.owner}</b> · Due: <b className="text-slate-700">{item.due}</b></p><button className="font-semibold text-blue-600">Review action</button></div></article>)}</section>
  </>;
}

function Count({ icon: Icon, value, label, tone }: { icon: React.ElementType; value: string; label: string; tone: "blue" | "emerald" | "amber" | "red" }) { const colours = { blue: "bg-blue-50 text-blue-600", emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", red: "bg-red-50 text-red-600" }; return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`w-fit rounded-xl p-3 ${colours[tone]}`}><Icon size={21} /></div><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></article>; }
