"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Eye, ListTodo, Search, UsersRound, X } from "lucide-react";
import MePageHeader from "../../../components/me/MePageHeader";

type TaskStatus = "Not Started" | "In Progress" | "Completed" | "Overdue";
type TaskPriority = "Low" | "Medium" | "High" | "Urgent";
type InstitutionalTask = {
  id: number;
  code: string;
  title: string;
  project: string;
  employee: string;
  initials: string;
  employeeNumber: string;
  department: string;
  assignedBy: string;
  assignedDate: string;
  dueDate: string;
  priority: TaskPriority;
  status: TaskStatus;
  progress: number;
  hours: number;
  expectedOutput: string;
  actualOutput: string;
  challenge: string;
};

const tasks: InstitutionalTask[] = [
  { id: 1, code: "TSK-1041", title: "Update university staff directory", project: "University Website", employee: "Godwin Malinde", initials: "GM", employeeNumber: "BU-ICT-026", department: "University Library", assignedBy: "Faculty Librarian", assignedDate: "02 Jul 2026", dueDate: "30 Jul 2026", priority: "High", status: "In Progress", progress: 78, hours: 42, expectedOutput: "Verified staff directory with updated profiles", actualOutput: "Profile data updated; final verification pending", challenge: "Some staff profiles have incomplete information." },
  { id: 2, code: "TSK-1042", title: "Prepare monthly content report", project: "Content Development", employee: "Aaron Kalamya", initials: "AK", employeeNumber: "BU-CD-001", department: "University Library", assignedBy: "Faculty Librarian", assignedDate: "01 Jul 2026", dueDate: "26 Jul 2026", priority: "Medium", status: "Completed", progress: 100, hours: 24, expectedOutput: "Approved July content report", actualOutput: "Monthly content report submitted and approved", challenge: "None reported." },
  { id: 3, code: "TSK-1043", title: "Implement performance dashboard", project: "Timesheet System", employee: "Brian Mwarisi", initials: "BM", employeeNumber: "BU-SD-003", department: "ICT Directorate", assignedBy: "Director ICT", assignedDate: "04 Jul 2026", dueDate: "25 Jul 2026", priority: "Urgent", status: "Overdue", progress: 68, hours: 56, expectedOutput: "Tested role-based performance dashboard", actualOutput: "Frontend complete; API integration outstanding", challenge: "Data endpoints are not yet available." },
  { id: 4, code: "TSK-1044", title: "Review institutional performance indicators", project: "Performance Monitoring", employee: "Gerald Kisombo", initials: "GK", employeeNumber: "BU-ME-004", department: "Planning Directorate", assignedBy: "Director Planning", assignedDate: "05 Jul 2026", dueDate: "31 Jul 2026", priority: "High", status: "In Progress", progress: 82, hours: 38, expectedOutput: "Validated KPI framework", actualOutput: "Three indicators validated; one under review", challenge: "One indicator lacks a reliable data source." },
  { id: 5, code: "TSK-1045", title: "Reconcile employee department records", project: "HR Data Quality", employee: "Jane Namusoke", initials: "JN", employeeNumber: "BU-HR-011", department: "Human Resources", assignedBy: "Director Human Resources", assignedDate: "03 Jul 2026", dueDate: "29 Jul 2026", priority: "High", status: "Completed", progress: 100, hours: 32, expectedOutput: "Validated employee-to-department mapping", actualOutput: "All active employee records reconciled", challenge: "Four records required supervisor confirmation." },
  { id: 6, code: "TSK-1046", title: "Compile quarterly expenditure analysis", project: "Financial Reporting", employee: "Sarah Atim", initials: "SA", employeeNumber: "BU-FIN-014", department: "Finance Department", assignedBy: "University Bursar", assignedDate: "10 Jul 2026", dueDate: "05 Aug 2026", priority: "Medium", status: "Not Started", progress: 0, hours: 0, expectedOutput: "Quarterly expenditure analysis report", actualOutput: "Not yet started", challenge: "Awaiting source schedules." },
];

export default function MeTasksPage() {
  const [search, setSearch] = useState("");
  const [department, setDepartment] = useState("All");
  const [status, setStatus] = useState("All");
  const [priority, setPriority] = useState("All");
  const [selected, setSelected] = useState<InstitutionalTask | null>(null);
  const departments = Array.from(new Set(tasks.map((task) => task.department)));
  const filtered = useMemo(() => tasks.filter((task) => {
    const term = search.toLowerCase();
    return (task.title.toLowerCase().includes(term) || task.employee.toLowerCase().includes(term) || task.code.toLowerCase().includes(term) || task.project.toLowerCase().includes(term)) && (department === "All" || task.department === department) && (status === "All" || task.status === status) && (priority === "All" || task.priority === priority);
  }), [search, department, status, priority]);

  return <><MePageHeader eyebrow="Institution-wide Work Monitoring" title="All Employee Tasks" description="Monitor assigned tasks, deadlines, outputs and completion progress across every employee and organizational unit." />
    <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-5"><Summary icon={ListTodo} label="All tasks" value="186" detail="Across all departments" tone="blue" /><Summary icon={CheckCircle2} label="Completed" value="132" detail="71% completion rate" tone="emerald" /><Summary icon={Clock3} label="In progress" value="38" detail="Currently being worked on" tone="blue" /><Summary icon={AlertTriangle} label="Overdue" value="9" detail="Require follow-up" tone="red" /><Summary icon={UsersRound} label="Employees with tasks" value="141" detail="95% workforce coverage" tone="amber" /></section>
    <section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 xl:flex-row xl:items-center xl:justify-between"><div className="relative w-full xl:max-w-sm"><Search size={18} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} type="search" placeholder="Search task, employee, project or code..." className="w-full rounded-lg border border-slate-300 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" /></div><div className="flex flex-wrap gap-3"><select value={department} onChange={(event) => setDepartment(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="All">All departments</option>{departments.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="All">All statuses</option><option>Not Started</option><option>In Progress</option><option>Completed</option><option>Overdue</option></select><select value={priority} onChange={(event) => setPriority(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="All">All priorities</option><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-325 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Task</th><th className="px-6 py-4">Employee</th><th className="px-6 py-4">Department</th><th className="px-6 py-4">Due date</th><th className="px-6 py-4">Priority</th><th className="px-6 py-4">Progress</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((task) => <tr key={task.id} className="hover:bg-slate-50"><td className="px-6 py-4"><p className="font-semibold text-slate-900">{task.title}</p><p className="mt-1 text-xs text-slate-500">{task.code} · {task.project}</p></td><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-xs font-bold text-blue-700">{task.initials}</div><div><p className="font-medium text-slate-800">{task.employee}</p><p className="text-xs text-slate-500">{task.employeeNumber}</p></div></div></td><td className="px-6 py-4 text-slate-600">{task.department}</td><td className="px-6 py-4 font-medium text-slate-700">{task.dueDate}</td><td className="px-6 py-4"><Priority value={task.priority} /></td><td className="min-w-45 px-6 py-4"><div className="mb-2 flex justify-between text-xs"><span className="text-slate-500">Completion</span><b>{task.progress}%</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${task.status === "Overdue" ? "bg-red-500" : task.status === "Completed" ? "bg-emerald-500" : "bg-blue-600"}`} style={{ width: `${task.progress}%` }} /></div></td><td className="px-6 py-4"><TaskStatusBadge value={task.status} /></td><td className="px-6 py-4"><button onClick={() => setSelected(task)} className="inline-flex items-center gap-2 font-semibold text-blue-600"><Eye size={17} /> View</button></td></tr>)}</tbody></table></div>
    </section>
    {selected ? <div className="fixed inset-0 z-60 flex justify-end bg-slate-950/50" role="dialog" aria-modal="true" aria-label={`View ${selected.title}`}><button className="absolute inset-0 cursor-default" aria-label="Close task details" onClick={() => setSelected(null)} /><aside className="scrollbar-hidden relative z-10 h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl"><div className="sticky top-0 flex items-start justify-between border-b border-slate-200 bg-white px-6 py-5"><div><p className="text-sm font-semibold text-blue-600">{selected.code}</p><h2 className="mt-1 text-xl font-bold text-slate-900">{selected.title}</h2><p className="mt-1 text-sm text-slate-500">{selected.project}</p></div><button onClick={() => setSelected(null)} aria-label="Close" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={21} /></button></div><div className="space-y-6 p-6"><div className="flex items-center gap-3 rounded-xl bg-slate-50 p-4"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-blue-100 font-bold text-blue-700">{selected.initials}</div><div><p className="font-bold text-slate-900">{selected.employee}</p><p className="text-sm text-slate-500">{selected.employeeNumber} · {selected.department}</p></div></div><section className="grid gap-4 sm:grid-cols-2"><Detail label="Assigned by" value={selected.assignedBy} /><Detail label="Assigned date" value={selected.assignedDate} /><Detail label="Due date" value={selected.dueDate} /><Detail label="Hours recorded" value={`${selected.hours} hours`} /><Detail label="Priority" value={selected.priority} /><Detail label="Status" value={selected.status} /></section><div><div className="mb-2 flex justify-between text-sm"><span className="font-semibold text-slate-700">Task progress</span><b>{selected.progress}%</b></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{ width: `${selected.progress}%` }} /></div></div><TextBlock title="Expected output" text={selected.expectedOutput} /><TextBlock title="Actual output" text={selected.actualOutput} /><TextBlock title="Reported challenge" text={selected.challenge} /></div></aside></div> : null}
  </>;
}

function Summary({ icon: Icon, label, value, detail, tone }: { icon: React.ElementType; label: string; value: string; detail: string; tone: "blue" | "emerald" | "amber" | "red" }) { const colours = { blue: "bg-blue-50 text-blue-600", emerald: "bg-emerald-50 text-emerald-600", amber: "bg-amber-50 text-amber-600", red: "bg-red-50 text-red-600" }; return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`w-fit rounded-xl p-3 ${colours[tone]}`}><Icon size={22} /></div><p className="mt-4 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></article>; }
function TaskStatusBadge({ value }: { value: TaskStatus }) { const styles = { "Not Started": "bg-slate-200 text-slate-600", "In Progress": "bg-blue-100 text-blue-700", Completed: "bg-emerald-100 text-emerald-700", Overdue: "bg-red-100 text-red-700" }; return <span className={`whitespace-nowrap rounded-full px-3 py-1 text-xs font-semibold ${styles[value]}`}>{value}</span>; }
function Priority({ value }: { value: TaskPriority }) { const styles = { Low: "bg-slate-100 text-slate-600", Medium: "bg-blue-100 text-blue-700", High: "bg-amber-100 text-amber-700", Urgent: "bg-red-100 text-red-700" }; return <span className={`rounded-full px-3 py-1 text-xs font-semibold ${styles[value]}`}>{value}</span>; }
function Detail({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-slate-800">{value}</p></div>; }
function TextBlock({ title, text }: { title: string; text: string }) { return <section className="rounded-xl border border-slate-200 p-5"><h3 className="font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></section>; }
